import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:developer';
import 'package:shared_preferences/shared_preferences.dart';
import 'logomodel.dart';

class Splash extends StatefulWidget {
  const Splash({super.key});

  @override
  State<Splash> createState() => _SplashState();
}

class _SplashState extends State<Splash> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Splash Screen"),
        centerTitle: true,
             ),
      body: Center(
        child: ElevatedButton(onPressed: (){
          //_postData();
             },
        child: Text("tap")),
      ),
         );
  }
 // // // Future<Autogenerated>postData() async {
 // //    try{
 // //      var response = await http
 // //          .post(Uri.parse("http://students.wissenerp.com/Login/get_logo"));
 // //      if(response.statusCode==200){
 // //        Map<String,dynamic>responseData=jsonDecode(response.body);
 // //        SharedPreferences prefs=await SharedPreferences.getInstance();
 // //        String logourl=responseData['logo_url'];
 // //        prefs.setString("logo", logourl);
 // //        log(logourl.toString());
 // //        return Autogenerated.fromJson(responseData);
 // //      }
 // //      else{
 // //        return Autogenerated();
 // //      }
 // //    }
 // //    catch(ex){
 // //      log(ex.toString());
 //    }
 //  }
}

